fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform fmt
        language: system
        types: [terraform]
        pass_filenames: false
        entry: terraform fmt
        args: [-write]

      - id: terraform-validate
        name: terraform validate
        language: system
        types: [terraform]
        pass_filenames: false
        entry: terraform validate
