fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: tofu-fmt
        name: tofu fmt
        language: system
        types: [terraform]
        pass_filenames: false
        entry: tofu fmt
        args: [-write]

      - id: tofu-validate
        name: tofu validate
        language: system
        types: [terraform]
        pass_filenames: false
        entry: tofu validate
