QueryLanguage: JSONata
Comment: RDS rotation main workflow.
StartAt: Prepare
TimeoutSeconds: 3600
States:
  Prepare:
    Type: Wait
    Seconds: 5
    Next: Find old database
    Assign:
      inputs: >-
        {% (
          $dbIdPrefix := "${tftpl.db_id_prefix}";
          {
            "dbIdPrefix": $dbIdPrefix,
            "newDbId": $exists($states.input.newDbId)
              ? $states.input.newDbId
              : $dbIdPrefix & $now("[Y0001][M01][D01]t[H01][m01][s01]", "+0900"),
            "snapshotId": $states.input.snapshotId
          }
        ) %}
  Find old database:
    Type: Task
    Comment: Find old database instances matching the specified DB ID prefix
    Arguments: {}
    Resource: arn:aws:states:::aws-sdk:rds:describeDBInstances
    Next: Check instance count
    Assign:
      matchedInstances: >-
        {% (
          $exists($states.result.DbInstances[0])
            ? $states.result.DbInstances[$substring(DbInstanceIdentifier, 0, $length($inputs.dbIdPrefix)) = $inputs.dbIdPrefix]
            : []
        ) %}
  Check instance count:
    Type: Choice
    Comment: >
      Check if there are too many old database instances matching the specified
      DB ID prefix to prevent conflicts with ongoing workflows.
    Choices:
      - Next: Unrecoverable error
        Condition: "{% (($count($matchedInstances)) > (1) and
          $not($exists($inputs.newDbId))) %}"
    Default: Restore DB instance from snapshot
    Assign:
      oldDb: "{% $exists($matchedInstances[0]) ? $matchedInstances[0] : null %}"
      oldDbId: "{% $exists($matchedInstances[0]) ?
        $matchedInstances[0].DbInstanceIdentifier : null %}"
  Restore DB instance from snapshot:
    Type: Task
    Arguments:
      DbInstanceIdentifier: "{% $inputs.newDbId %}"
      DbSnapshotIdentifier: "{% $inputs.snapshotId %}"
      DbSubnetGroupName: '{% $oldDb ? $oldDb.DbSubnetGroup.DbSubnetGroupName :
        "${tftpl.db_subnet_group_name}" %}'
      PubliclyAccessible: '{% $oldDb ? $oldDb.PubliclyAccessible :
        "${tftpl.publicly_accessible}" %}'
      VpcSecurityGroupIds: '{% $oldDb ? $oldDb.VpcSecurityGroups[].VpcSecurityGroupId
        : ["${join("\", \"", tftpl.vpc_security_group_ids)}"] %}'
      Tags:
        - Key: Project
          Value: aws-rds-rotation
    Resource: arn:aws:states:::aws-sdk:rds:restoreDBInstanceFromDBSnapshot
    Next: Wait for RDS ready
    Catch:
      - ErrorEquals:
          - Rds.DbInstanceAlreadyExistsException
        Next: Wait for RDS ready
        Comment: Skip if instance already exists
  Wait for RDS ready:
    Type: Task
    Resource: arn:aws:states:::states:startExecution.sync:2
    Arguments:
      StateMachineArn: ${tftpl.wait_for_rds_ready_state_machine_arn}
      Input:
        AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID: "{% $states.context.Execution.Id %}"
        dbId: "{% $inputs.newDbId %}"
        waitSeconds: 30
    Next: Run SQL queries
    Catch:
      - ErrorEquals:
          - InstanceRestorationFailed
        Next: Unrecoverable error
        Comment: Instance restoration failed, manual intervention may be needed.
  Run SQL queries:
    Type: Task
    Resource: arn:aws:states:::lambda:invoke
    Output: "{% $states.result.Payload %}"
    Arguments:
      Payload: "{% $states.input %}"
      FunctionName: ${tftpl.lambda_function_name}
    Retry:
      - ErrorEquals:
          - Lambda.ServiceException
          - Lambda.AWSLambdaException
          - Lambda.SdkClientException
          - Lambda.TooManyRequestsException
        IntervalSeconds: 1
        MaxAttempts: 3
        BackoffRate: 2
        JitterStrategy: FULL
    Next: Update domain record to new database
  Update domain record to new database:
    Type: Task
    Arguments:
      ChangeBatch:
        Changes:
          - Action: UPSERT
            ResourceRecordSet:
              Name: ${tftpl.route53_domain_name}
              Type: CNAME
              Ttl: 60
              ResourceRecords:
                - Value: "{% $dbDomain %}"
      HostedZoneId: ${tftpl.route53_hosted_zone_id}
    Resource: arn:aws:states:::aws-sdk:route53:changeResourceRecordSets
    Next: Old instance exists?
  Old instance exists?:
    Type: Choice
    Choices:
      - Next: Delete old database
        Condition: "{% $oldDbId != null %}"
    Default: No instance to delete
  Unrecoverable error:
    Type: Fail
    Error: "{% $states.error.Error %}"
    Cause: "{% $states.error.Cause %}"
    Comment: Manual human intervention is needed.
  Delete old database:
    Type: Task
    Arguments:
      DbInstanceIdentifier: "{% $oldDbId %}"
      SkipFinalSnapshot: true
    Resource: arn:aws:states:::aws-sdk:rds:deleteDBInstance
    End: true
  No instance to delete:
    Type: Pass
    End: true
