QueryLanguage: JSONata
Comment: Wait for the RDS DB instance to become available before running SQL queries.
StartAt: Check DB instance status
TimeoutSeconds: 1200
States:
  Check DB instance status:
    Type: Task
    Arguments:
      DbInstanceIdentifier: "{% $states.input.dbId %}"
    Resource: arn:aws:states:::aws-sdk:rds:describeDBInstances
    Assign:
      dbStatus: "{% $states.result.DbInstances[0].DbInstanceStatus %}"
      dbDomain: "{% $states.result.DbInstances[0].Endpoint ?
        $states.result.DbInstances[0].Endpoint.Address : 'n/a' %}"
    Next: Is DB instance available?
  Wait for DB instance ready:
    Type: Wait
    Seconds: "{% $states.input.waitSeconds %}"
    Next: Check DB instance status
  Is DB instance available?:
    Type: Choice
    Choices:
      - Condition: '{% ($dbStatus) = ("available") %}'
        Next: Completed
      - Next: Wait for DB instance ready
        Condition: '{% ( $dbStatus in ["creating", "starting", "storage-initialization",
          "configuring-enhanced-monitoring", "modifying"] ) %}'
    Default: Restoration failed
  Restoration failed:
    Type: Fail
    Error: InstanceRestorationFailed
    Cause: Failed to restore database instance from snapshot.
    Comment: Instance restoration entered unexpected status. Please diagnose the RDS events.
  Completed:
    Type: Pass
    End: true
    Output: "{% { 'dbDomain': $dbDomain, 'dbStatus': $dbStatus } %}"
    Comment: The RDS DB instance is available and ready for use.
